// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMfKDPbH23uU8d_B-OFHVZLSCVAbXtHPA',
    appId: '1:880041675290:web:89a0ab8b7032bcf7401fa3',
    messagingSenderId: '880041675290',
    projectId: 'medic-4884e',
    authDomain: 'medic-4884e.firebaseapp.com',
    storageBucket: 'medic-4884e.appspot.com',
    measurementId: 'G-VQSB1KL4G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWv-vxG9LurojbNyWSmVVuxbY_R1Svr4',
    appId: '1:880041675290:android:83a3eee2980461a2401fa3',
    messagingSenderId: '880041675290',
    projectId: 'medic-4884e',
    storageBucket: 'medic-4884e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoZq6UhMyUkg09JoK4Rwve6_s89mAK14',
    appId: '1:880041675290:ios:617111ffc7d62f52401fa3',
    messagingSenderId: '880041675290',
    projectId: 'medic-4884e',
    storageBucket: 'medic-4884e.appspot.com',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoZq6UhMyUkg09JoK4Rwve6_s89mAK14',
    appId: '1:880041675290:ios:617111ffc7d62f52401fa3',
    messagingSenderId: '880041675290',
    projectId: 'medic-4884e',
    storageBucket: 'medic-4884e.appspot.com',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMfKDPbH23uU8d_B-OFHVZLSCVAbXtHPA',
    appId: '1:880041675290:web:524e498b90a9b156401fa3',
    messagingSenderId: '880041675290',
    projectId: 'medic-4884e',
    authDomain: 'medic-4884e.firebaseapp.com',
    storageBucket: 'medic-4884e.appspot.com',
    measurementId: 'G-N9ECW9006B',
  );
}
